### ISSUE TITLE
opensim-matlab container

### ISSUE THREAD

**Issue by ahmadsheikhzada** [opensim-org/opensim-containers#17] opened 2022-10-25 21:01 UTC
Hi,

We are interested in containerizing opensim with matlab if that is a possibility. We want to do this for some users of our HPC system. Since matlab is a licensed software we were wondering if we can build the container with Matlab Compiler Runtime. We do not know how opensim works with matlab though. Do you think the idea will work?

Thanks,
Ahmad Shiekhzada

**Comment by aymanhab** [comment] 2022-10-26 18:01
Hi Ahmad, 

As you pointed out Matlab has specific license requirements that we'd prefer not to deal with. If you have questions about distributing Matlab runtime in a Docker container, I'd suggest you consult with Mathworks/Matlab. On the technical side I don't see a problem with that as long as the license is not required separately or a license for your institution is available to your users, however you'll need to build the image yourself. If there're issues related to our containers then please feel free to open another issue, otherwise I'd recommend you close this issue as it's not a bug/issue on our side. Thank you

**Closed** 2022-10-26 20:38 UTC
